name: "compile-check-blink"
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
jobs:
  nix-flake-check:
    runs-on: ubuntu-22.04  # Work around https://github.com/containers/bubblewrap/issues/632
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v29
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: Compile test
      run: |
        nix develop --command make -C blink compile

    - name: Formatter check
      run: |
        nix fmt
        git diff --exit-code
